language: php
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - vendor/bin/tester tests -s

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
    include:
        -   name: Nette Code Checker
            install:
                - travis_retry composer create-project nette/code-checker temp/code-checker ^3 --no-progress
            script:
                - php temp/code-checker/code-checker -i tests/fixtures


        -   name: Nette Coding Standard
            php: 7.2
            install:
                - travis_retry composer create-project nette/coding-standard temp/coding-standard ^3 --no-progress
            script:
                - php temp/coding-standard/ecs check


        -   stage: Static Analysis (informative)
            script:
                - composer run-script phpstan


    allow_failures:
        -   stage: Static Analysis (informative)


sudo: false

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
