name: ci

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  phpunit:
    name: build
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    env:
      PHP_CMD: '/usr/local/php/bin/php'
      COMPOSER_CMD: '/usr/local/bin/composer'

    container: charescape/web:6.1.1

    steps:
      - uses: actions/checkout@v3

      - run: sudo ln -s /usr/local/php/bin/php /usr/local/bin/php
      - run: sudo ln -s /usr/local/php/bin/php /bin/php

      - run: php -v

      - run: composer self-update -vvv

      - name: Install dependencies
        run: |
          rm -rf vendor/
          rm -f composer.lock
          composer install --no-interaction

      - name: Tester
        run: vendor/bin/tester tests -s
