name: ci

on:
  push:
    branches:
      - master
      - main
  pull_request:

env:
  COMPOSER_INSTALL_FLAGS: "--prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi"

jobs:
  phpunit:
    name: PHP ${{ matrix.php-version }} on ${{ matrix.os-version }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ${{ matrix.os-version }}

    strategy:
      fail-fast: false
      matrix:
        os-version: [ubuntu-20.04, ubuntu-22.04]
        php-version: ['7.4', '8.0', '8.1', '8.2']

    steps:
      - name: Generate french locale
        run: sudo locale-gen fr_FR.UTF-8

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: pecl
          extensions: curl, dom, imagick, intl, mbstring, tokenizer, memcached, mysql, pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, sqlite
          ini-values: date.timezone='UTC', session.save_path="${{ runner.temp }}"

      - name: Install dependencies
        run: |
          rm -rf vendor/
          rm -f composer.lock
          composer self-update -vvv
          composer install $COMPOSER_INSTALL_FLAGS

      - name: Tester
        run: vendor/bin/tester tests -s

      - name: Actual
        run: for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
